version: '2.1'
services:
    redis:
        image: 'redis:5.0.5'
        # command: redis-server --requirepass redispass

    webserver:
        image: airflow-docker-1.10.13:latest
        container_name: airflow-webserver
        volumes:
            - /home/pradipta.r/airflow-docker-1.10.13/dags:/usr/local/airflow/dags
        ports:
            - 8080:8080
        restart: always
        depends_on:
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=_ZqQBBLOOKbgcGMe30_sN3FlDAXFVIa2sYe3dceDExE=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        volumes:
            - /home/pradipta/airflow-docker-1.10.13/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: airflow-docker-1.10.13:latest
        container_name: airflow-flower
        restart: always
        depends_on:
            - redis
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-flower.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        environment:
            - EXECUTOR=Celery
            # - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: airflow-docker-1.10.13:latest
        container_name: airflow-scheduler
        restart: always
        depends_on:
            - webserver
        volumes:
            - /home/pradipta/airflow-docker-1.10.13/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=_ZqQBBLOOKbgcGMe30_sN3FlDAXFVIa2sYe3dceDExE=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: scheduler

    worker:
        image: airflow-docker-1.10.13:latest
        container_name: airflow-worker
        restart: always
        depends_on:
            - scheduler
        volumes:
            - /home/pradipta/airflow-docker-1.10.13/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=_ZqQBBLOOKbgcGMe30_sN3FlDAXFVIa2sYe3dceDExE=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: worker
